INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(1, 'Háztartási gépek');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(2, 'TV és szórakozás');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(3, 'Telefon, Tablet, Laptop');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(4, 'Számítástechnika');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(5, 'Fotó-Videó, Okos eszközök');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(6, 'Szupermarket');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(7, 'Otthon, barkács, állattartás');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(8, 'Játékok, Baba, Mama');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(9, 'Divat, ékszerek és kiegészítők');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(10, 'Szépségápolás');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(11, 'Sport és szabadidő');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(12, 'Könyvek, Filmek és Irodaszerek');
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name) VALUES(13, 'Autó- és motor felszerelések');


INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(1, 'Mosógépek',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(2, 'Szárítógépek',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(3, 'Hűtőszekrények',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(4, 'Kombinált hűtők',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(5, 'Páraelszívók',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(6, 'Beépíthető főzőlapok',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(7, 'Beépíthető sütők',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(8, 'Klímák',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(9, 'Légtisztítók',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(10, 'Porszívók',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(11, 'Vasalók',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(12, 'Automata expressz kávéfőzők',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(13, 'Kapszulás kávéfőzők',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(14, 'Mixerek',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(15, 'Robotgépek',1);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(16, 'Televíziók HD és Full HD',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(17, 'Televízió 4K Ultra HD',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(18, 'TV állványok és fali konzolok',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(19, 'Távirányítók',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(20, 'Kábelek és adapterek',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(21, 'TV antennák és kiegészítók',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(22, 'Hangprojektorok',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(23, 'Házimozi rendszerek',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(24, 'Hangrendszerek',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(25, 'Médialejátszók',2);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(25, 'Mobiltelefonok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(26, 'Akciós telefonok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(27, 'iPhoneH',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(28, 'Huawei készülékek',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(29, 'Külső akkumulátorok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(30, 'Telefon akkumulátorok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(31, 'Memóriakártyák',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(32, 'Védőfóliák',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(33, 'Fej- és fülhallgatók',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(34, 'Bluetooth headsetek',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(35, 'Laptop, notebook',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(36, 'Laptopok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(37, 'Akciós laptopok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(38, 'ASUS laptopok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(39, 'Lenovo laptopok',3);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(40, 'Asztali számítógépek',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(41, 'Monitorok',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(42, 'Gamer PC-k',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(43, 'Gamer laptopok',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(44, 'Videókártyák',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(45, 'SSD meghajtók',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(46, 'Merevlemezek',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(47, 'Memóriák',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(48, 'Alaplapok',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(49, 'Wifi routerek',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(50, 'Billentyűzetek',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(51, 'Egerek',4);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(52, 'Fényképezőgépek',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(53, 'Digitális fényképezőgépek',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(54, 'Táskák, hátizsákok',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(55, 'Háromlábú állványok',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(56, 'Objektívek',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(57, 'Vakuk',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(58, 'Memóriakártya',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(59, 'Videókamerák',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(60, 'Sportkamerák',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(61, 'Tokok, táskák és védőházak',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(62, 'Nagyítók',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(63, 'Okosóra kiegészítők',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(64, 'Okos otthon',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(65, 'Okos világítás',5);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(66, 'Tészta',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(67, 'Tea',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(68, 'Kávé',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(69, 'Édességek',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(70, 'Ásványvíz',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(71, 'Szénsavas üdítők',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(72, 'Energiaitalok',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(73, 'Szörpök',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(74, 'Parfümök',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(75, 'Baba tápszerek',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(76, 'Tisztítószerek',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(77, 'Kézfertőtlenítők',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(78, 'Táplálékkiegészítők',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(79, 'Por alapú energiaitalok',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(80, 'Kutyaeledel',6);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(81, 'Fűnyíró gépek',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(82, 'Fűkaszák',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(83, 'Magas nyomású mosók',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(84, 'Kerti grillezők',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(85, 'Medencék',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(86, 'Gyerek medencék',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(87, 'Izzók',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(88, 'Lámpák',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(89, 'Matracok',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(90, 'Fedőmatracok',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(91, 'Ágyak',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(92, 'Kanapék',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(93, 'Székek',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(94, 'Asztalok',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(95, 'Párnák',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(96, 'Paplanok',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(97, 'Mosószerek',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(98, 'Öblítőszerek',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(99, 'Felmosószerek',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(100, 'Ruhaszárítók',7);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(101, 'Babajátékok',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(102, 'Gyerekkonyhák',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(103, 'Lányos játékok',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(104, 'Fiús játékok',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(105, 'LEGO',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(106, 'Társasjátékok',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(107, 'Elektromos kisautók és gyermek járművek',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(108, 'Triciklik',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(109, 'Gyerekházak',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(110, 'Sátrak',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(111, 'Csúszdák',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(112, 'Hinták',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(113, 'Etetőszékek',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(114, 'Ruházat és cipők',8);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(115, 'Pólok',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(116, 'Ruhák',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(117, 'Farmernadrágok',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(118, 'Fürdőruhák',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(119, 'Tornacipők',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(120, 'Félcipők, magassrakúk',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(121, 'Szandálok',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(122, 'Karórák',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(123, 'Napszemüvegek',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(124, 'Kapucnis felsők',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(125, 'Női sportruházat',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(126, 'Férfi sportruházat',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(127, 'Női fürdőruhák',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(128, 'Férfi fürdőnadrágok',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(129, 'Strand kiegészítők',9);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(130, 'Női parfümök',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(131, 'Férfi parfümök',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(132, 'Köröm és sarokreszelők',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(133, 'Kézfertőtlenítők',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(134, 'Kézfertőtlenítő szappanok',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(135, 'Szappanok',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(136, 'Tusfürdő',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(137, 'Testápoló',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(138, 'Kézkrémek',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(139, 'Hajsampon',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(140, 'Hajbalzsam',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(141, 'Dezodorok és izzadsággátlók',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(142, 'Epilátorok',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(143, 'Hajvasalók',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(144, 'Hajszárítók',10);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(145, 'Haspadok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(146, 'Futópadok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(147, 'Szobabicikli',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(148, 'Taposógéoek',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(149, 'Súlyzók',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(150, 'Labdák',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(151, 'Sport pólók',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(152, 'Sport nadrágok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(153, 'Kerékpárok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(154, 'Kerékpáros gyerekülések',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(155, 'Túrahátizsákok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(156, 'Sátrak',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(157, 'Rollerek',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(158, 'Görkorcsolyák',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(159, 'Trambulinok',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(160, 'Horgászat',11);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(161, 'Hangoskönyvek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(162, 'Újságok, magazinok',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(163, 'Irodalom',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(164, 'Gyerekkönyvek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(165, 'Ifjúsági könyvek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(166, 'Utazás',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(167, 'Sikerkönyvek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(168, 'Filmek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(169, 'Számológépek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(170, 'Irattartók',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(171, 'Naplók és naptárak',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(172, 'Nyomtatók',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(173, 'Fénymásoló papírok',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(174, 'Fotópapírok',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(175, 'Tolltartó',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(176, 'Füzetek',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(177, 'Korrektor és radír',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(178, 'Geometriai eszközök',12);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(179, 'GPS Navigációs rendszerek',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(180, 'Mélynyomók és hangszórók',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(181, 'DVR autókamerák',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(182, 'Rádióállomások és radardetektorok',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(183, 'Autós üléshuzatok',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(184, 'Kerékpárszállítók',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(185, 'Tetőcsomagtartók',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(186, 'Tetőboxok',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(187, 'Autós hűtők',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(188, 'Autós emelők',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(189, 'Dísztárcsák',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(190, 'Nyári gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(191, 'Téli gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(192, 'All season',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(193, 'CONTINENTAL gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(194, 'Michelin gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(195, 'Pirelli gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(196, 'Hankook gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(197, 'Dunlop gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(198, 'GoodYear gumik',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(199, 'Motorkerékpárok és robogók',13);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id) VALUES(200, 'Elektromos járművek',13);


INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(1, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\a4mMgNi6YgizoLMm.PNG',1,0);
INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(2, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\DoOa4xACa9Kai9Ut.PNG',1,0);
INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(3, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\XhPAEcKa5330tC8j.PNG',1,0);