INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(1, 'Háztartási gépek',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(2, 'TV és szórakozás',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(3, 'Telefon, Tablet, Laptop',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(4, 'Számítástechnika',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(5, 'Fotó-Videó, Okos eszközök',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(6, 'Szupermarket',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(7, 'Otthon, barkács, állattartás',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(8, 'Játékok, Baba, Mama',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(9, 'Divat, ékszerek és kiegészítők',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(10, 'Szépségápolás',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(11, 'Sport és szabadidő',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(12, 'Könyvek, Filmek és Irodaszerek',0);
INSERT INTO PRODUCT_CATEGORIES (id, product_category_name, is_deleted) VALUES(13, 'Autó- és motor felszerelések',0);


INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(1, 'Mosógépek',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(2, 'Szárítógépek',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(3, 'Hűtőszekrények',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(4, 'Kombinált hűtők',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(5, 'Páraelszívók',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(6, 'Beépíthető főzőlapok',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(7, 'Beépíthető sütők',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(8, 'Klímák',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(9, 'Légtisztítók',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(10, 'Porszívók',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(11, 'Vasalók',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(12, 'Automata expressz kávéfőzők',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(13, 'Kapszulás kávéfőzők',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(14, 'Mixerek',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(15, 'Robotgépek',1,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(16, 'Televíziók HD és Full HD',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(17, 'Televízió 4K Ultra HD',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(18, 'TV állványok és fali konzolok',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(19, 'Távirányítók',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(20, 'Kábelek és adapterek',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(21, 'TV antennák és kiegészítók',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(22, 'Hangprojektorok',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(23, 'Házimozi rendszerek',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(24, 'Hangrendszerek',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(25, 'Médialejátszók',2,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(201, 'Mobiltelefonok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(26, 'Akciós telefonok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(27, 'iPhoneH',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(28, 'Huawei készülékek',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(29, 'Külső akkumulátorok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(30, 'Telefon akkumulátorok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(31, 'Memóriakártyák',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(32, 'Védőfóliák',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(33, 'Fej- és fülhallgatók',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(34, 'Bluetooth headsetek',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(35, 'Laptop, notebook',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(36, 'Laptopok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(37, 'Akciós laptopok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(38, 'ASUS laptopok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(39, 'Lenovo laptopok',3,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(40, 'Asztali számítógépek',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(41, 'Monitorok',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(42, 'Gamer PC-k',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(43, 'Gamer laptopok',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(44, 'Videókártyák',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(45, 'SSD meghajtók',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(46, 'Merevlemezek',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(47, 'Memóriák',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(48, 'Alaplapok',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(49, 'Wifi routerek',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(50, 'Billentyűzetek',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(51, 'Egerek',4,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(52, 'Fényképezőgépek',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(53, 'Digitális fényképezőgépek',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(54, 'Táskák, hátizsákok',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(55, 'Háromlábú állványok',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(56, 'Objektívek',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(57, 'Vakuk',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(58, 'Memóriakártya',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(59, 'Videókamerák',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(60, 'Sportkamerák',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(61, 'Tokok, táskák és védőházak',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(62, 'Nagyítók',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(63, 'Okosóra kiegészítők',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(64, 'Okos otthon',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(65, 'Okos világítás',5,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(66, 'Tészta',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(67, 'Tea',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(68, 'Kávé',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(69, 'Édességek',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(70, 'Ásványvíz',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(71, 'Szénsavas üdítők',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(72, 'Energiaitalok',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(73, 'Szörpök',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(74, 'Parfümök',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(75, 'Baba tápszerek',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(76, 'Tisztítószerek',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(77, 'Kézfertőtlenítők',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(78, 'Táplálékkiegészítők',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(79, 'Por alapú energiaitalok',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(80, 'Kutyaeledel',6,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(81, 'Fűnyíró gépek',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(82, 'Fűkaszák',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(83, 'Magas nyomású mosók',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(84, 'Kerti grillezők',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(85, 'Medencék',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(86, 'Gyerek medencék',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(87, 'Izzók',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(88, 'Lámpák',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(89, 'Matracok',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(90, 'Fedőmatracok',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(91, 'Ágyak',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(92, 'Kanapék',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(93, 'Székek',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(94, 'Asztalok',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(95, 'Párnák',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(96, 'Paplanok',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(97, 'Mosószerek',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(98, 'Öblítőszerek',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(99, 'Felmosószerek',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(100, 'Ruhaszárítók',7,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(101, 'Babajátékok',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(102, 'Gyerekkonyhák',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(103, 'Lányos játékok',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(104, 'Fiús játékok',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(105, 'LEGO',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(106, 'Társasjátékok',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(107, 'Elektromos kisautók és gyermek járművek',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(108, 'Triciklik',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(109, 'Gyerekházak',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(110, 'Sátrak',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(111, 'Csúszdák',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(112, 'Hinták',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(113, 'Etetőszékek',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(114, 'Ruházat és cipők',8,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(115, 'Pólok',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(116, 'Ruhák',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(117, 'Farmernadrágok',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(118, 'Fürdőruhák',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(119, 'Tornacipők',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(120, 'Félcipők, magassrakúk',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(121, 'Szandálok',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(122, 'Karórák',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(123, 'Napszemüvegek',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(124, 'Kapucnis felsők',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(125, 'Női sportruházat',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(126, 'Férfi sportruházat',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(127, 'Női fürdőruhák',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(128, 'Férfi fürdőnadrágok',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(129, 'Strand kiegészítők',9,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(130, 'Női parfümök',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(131, 'Férfi parfümök',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(132, 'Köröm és sarokreszelők',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(133, 'Kézfertőtlenítők',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(134, 'Kézfertőtlenítő szappanok',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(135, 'Szappanok',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(136, 'Tusfürdő',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(137, 'Testápoló',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(138, 'Kézkrémek',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(139, 'Hajsampon',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(140, 'Hajbalzsam',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(141, 'Dezodorok és izzadsággátlók',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(142, 'Epilátorok',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(143, 'Hajvasalók',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(144, 'Hajszárítók',10,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(145, 'Haspadok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(146, 'Futópadok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(147, 'Szobabicikli',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(148, 'Taposógéoek',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(149, 'Súlyzók',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(150, 'Labdák',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(151, 'Sport pólók',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(152, 'Sport nadrágok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(153, 'Kerékpárok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(154, 'Kerékpáros gyerekülések',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(155, 'Túrahátizsákok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(156, 'Sátrak',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(157, 'Rollerek',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(158, 'Görkorcsolyák',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(159, 'Trambulinok',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(160, 'Horgászat',11,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(161, 'Hangoskönyvek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(162, 'Újságok, magazinok',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(163, 'Irodalom',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(164, 'Gyerekkönyvek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(165, 'Ifjúsági könyvek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(166, 'Utazás',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(167, 'Sikerkönyvek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(168, 'Filmek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(169, 'Számológépek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(170, 'Irattartók',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(171, 'Naplók és naptárak',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(172, 'Nyomtatók',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(173, 'Fénymásoló papírok',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(174, 'Fotópapírok',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(175, 'Tolltartó',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(176, 'Füzetek',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(177, 'Korrektor és radír',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(178, 'Geometriai eszközök',12,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(179, 'GPS Navigációs rendszerek',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(180, 'Mélynyomók és hangszórók',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(181, 'DVR autókamerák',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(182, 'Rádióállomások és radardetektorok',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(183, 'Autós üléshuzatok',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(184, 'Kerékpárszállítók',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(185, 'Tetőcsomagtartók',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(186, 'Tetőboxok',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(187, 'Autós hűtők',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(188, 'Autós emelők',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(189, 'Dísztárcsák',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(190, 'Nyári gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(191, 'Téli gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(192, 'All season',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(193, 'CONTINENTAL gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(194, 'Michelin gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(195, 'Pirelli gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(196, 'Hankook gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(197, 'Dunlop gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(198, 'GoodYear gumik',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(199, 'Motorkerékpárok és robogók',13,0);
INSERT INTO PRODUCT_SUBCATEGORIES (id, name, product_category_id, is_deleted) VALUES(200, 'Elektromos járművek',13,0);


INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(1, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\a4mMgNi6YgizoLMm.PNG',1,0);
INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(2, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\DoOa4xACa9Kai9Ut.PNG',1,0);
INSERT INTO TOP_NEWS_IMAGES (id, file_path, is_active, is_deleted) VALUES(3, 'D:\\Programming\\Own\\webshop\\photos\\top-photos\\XhPAEcKa5330tC8j.PNG',1,0);

INSERT INTO COUNTRIES(id, name, is_deleted) VALUES(1, 'Magyarország',0);
INSERT INTO COUNTRIES(id, name, is_deleted) VALUES(2, 'România',0);
INSERT INTO COUNTRIES(id, name, is_deleted) VALUES(3, 'United Kingdom',0);
INSERT INTO COUNTRIES(id, name, is_deleted) VALUES(4, 'Italiano',0);

INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(1, 'Budapest', 1,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(2, 'Szeged', 1,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(3, 'Debrecen', 1,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(4, 'Kecskemét', 1,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(5, 'Nyíregyháza', 1,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(6, 'Miercurea-Ciuc(Csíkszereda)', 2,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(7, 'Odorheiu Secuiesc(Székelyudvarhely)', 2,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(8, 'Oradea(Nagyvárad)', 2,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(9, 'Cluj-Napoca(Kolozsvár)', 2,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(10, 'Târgu Mureș(Marosvásárhely)', 2,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(11, 'London', 3,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(12, 'Birmingham', 3,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(13, 'Oxford', 3,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(14, 'Newport', 3,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(15, 'Manchester', 3,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(16, 'Roma', 4,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(17, 'Tivoli', 4,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(18, 'Benevento', 4,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(19, 'Potenza', 4,0);
INSERT INTO PLACES(id, name, country_id, is_deleted) VALUES(20, 'Firenze', 4,0);

INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (1,'1052, Semmelweis utca',1,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (2,'1091, Kálvin tér',1,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (3,'6725, Szentháromság utca',2,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (4,'6725, Petőfi sgrt.',2,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (5,'4024, Csapó utca',3,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (6,'4027, Füredi utca',3,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (7,'6000, Horog utca',4,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (8,'6000, Szolnokhegy tanya',4,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (9,'4400, Ady Endre utca',5,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (10,'4400, Szent István utca',5,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (11,'530102, Bulevardul Timișoarei',6,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (12,'530222, strada Petőfi Sándor',6,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (13,'535600, Strada Pieţii',7,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (14,'535600, Strada Croitorilor',7,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (15,'410080, Strada Horea',8,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (16,'410526, Strada Dobrogei',8,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (17,'400000, Strada Liviu Rebreanu',9,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (18,'400000, Strada Iuliu Maniu',9,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (19,'540194, Strada Nicolae Bălcescu',10,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (20,'540494, Strada Predeal',10,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (21,'W1K 1QZ, Old Park Ln',11,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (22,'W1D 7HJ, Denman St',11,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (23,'B12 0JD, 191-194 Bradford St',12,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (24,'B9 4AA, The Custard Factory, Gibb St',12,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (25,'OX1 3BG, Radcliffe Sq',13,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (26,'OX1 2EW, Hythe Bridge St',13,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (27,'NP20 2DW, The Old Town Dock',14,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (28,'NP19 8JH, Chepstow Rd',14,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (29,'M1 2PG, London Rd',15,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (30,'M43 6LB, Haddon Hall Rd',15,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (31,'00185, Via Cavour',16,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (32,'00185, Via Petrarca',16,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (33,'00019, Via Empolitana',17,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (34,'00019, Tivoli',17,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (35,'82100, Viale Atlantici',18,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (36,'82100, Via Giuseppe Manciotti',18,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (37,'85100, Via Mantova',19,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (38,'85100, Contrada Canale',19,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (39,'50123, Via, Borgo Ognissanti',20,0);
INSERT INTO STREETS(id, name, place_id, is_deleted) VALUES (40,'50137, Viale Augusto Righi',20,0);

